# Generated by Django 3.2.3 on 2021-06-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='opening_crawl',
            field=models.TextField(null=True),
        ),
    ]
